name: OCI Minecraft

on:
  schedule:
    - cron: '*/2 * * * *'  # cada 2 minutos
  workflow_dispatch:

jobs:
  run-minecraft:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install OCI CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --user oci-cli

      - name: Run script
        run: php "time php runner.php"
